### Introdução ao Pandas

In [3]:
#O método series no pandas cria matrizes unidimensionais, semelhantes a uma coluna do excel ou uma lista do Python.

import pandas as pd
import numpy as np

serie_inicial = pd.Series(np.random.rand(5), index=['A', 'B', 'C', 'D', 'E'])
print(serie_inicial)

serie_lista = pd.Series(['Python', 'Java', 'C++', 'JavaScript'])
print(serie_lista)

A    0.865305
B    0.290338
C    0.143719
D    0.518570
E    0.746796
dtype: float64
0        Python
1          Java
2           C++
3    JavaScript
dtype: object

In [4]:
#A partir de Series
dicionario = {
    "empresa": pd.Series(["Google", "Amazon", "Facebook"], index=['2019', '2020', '2021']),
    "preco": pd.Series([1000, 2000, 3000], index=['2019', '2020', '2021']),
    "volume": pd.Series([100, 200, 300], index=['2019', '2020', '2021'])
}

dataframe = pd.DataFrame(dicionario)
print(dataframe)

       empresa  preco  volume
2019    Google   1000     100
2020    Amazon   2000     200
2021  Facebook   3000     300

In [5]:
#DataFrame é uma estrutura de dados bidimensional, semelhante a uma tabela, onde os dados são organizados em linhas e colunas.

#Criando um DataFrame 3x3 a partir de um dicionário

dicionario = {
    "empresa": ["Google", "Amazon", "Facebook"],
    "preco": [1000, 2000, 3000],
    "volume": [100, 200, 300]
}

dataframe = pd.DataFrame(dicionario, index=['2019', '2020', '2021'])
columns = ['empresa', 'preco', 'volume', 'teste']

dataframe

       empresa  preco  volume
2019    Google   1000     100
2020    Amazon   2000     200
2021  Facebook   3000     300

In [6]:
#A partir de dicionário

dicionario_cotacoes = {'WEG3': 30.00, 'VALE3': 60.00, 'PETR4': 25.00}
serie_cotacoes = pd.Series(dicionario_cotacoes)
print(serie_cotacoes)
print(serie_cotacoes['WEG3'])
serie_cotacoes['WEG3']

WEG3     30.0
VALE3    60.0
PETR4    25.0
dtype: float64
30.0

np.float64(30.0)

In [7]:
#Desafio 1

serie = pd.Series([10, 20, 30, 40, 50])
print(serie)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [8]:
#Desafio 2
import random
import matplotlib.pyplot as plt

cotacao_inicial = float(input('Informe a cotação inicial da ação: '))
numero_dias = int(input('Informe o número de dias para simulação: '))
lista_cotacoes = [cotacao_inicial]
lista_dias = [0]
volatilidade = 0.01  # 1% de volatilidade diária

for i in range(1, numero_dias + 1):
    # Gera um retorno diário aleatório baseado na volatilidade
    retorno_diario = np.random.normal(0, volatilidade)
    nova_cotacao = lista_cotacoes[-1] * (1 + retorno_diario)
    lista_cotacoes.append(nova_cotacao)
    lista_dias.append(i)
    print(f'Dia {i}: Cotação = {nova_cotacao:.2f}')


print(lista_cotacoes)

plt.plot(lista_cotacoes)

ValueError: could not convert string to float: ''

In [ ]:
#Desafio 3

dicionario = {
    'nomes': ['Weg', 'Petrobras', 'Vale', 'Petrobras', 'Lojas Renner'],
    'tickes': ['WEG3', 'PETR4', 'VALE3', 'PETR4', 'LREN3'],
    'cotacoes': [20, 30, 40, 12, 35],
    'preco_sobre_lucro': [25, 6, 12, 7, 25],
    'volumes': [5000, 1000, 4000, 7000, 1200]
}

df_info_empresas = pd.DataFrame(dicionario)
df_info_empresas

          nomes tickes  cotacoes  preco_sobre_lucro  volumes
0           Weg   WEG3        20                 25     5000
1     Petrobras  PETR4        30                  6     1000
2          Vale  VALE3        40                 12     4000
3     Petrobras  PETR4        12                  7     7000
4  Lojas Renner  LREN3        35                 25     1200

### Manipulação do index

In [ ]:
#Como criar um index personalizado = .set_index()

dicionario = {'empresa': ['Weg', 'Petrobras', 'Vale', 'Petrobras', 'Lojas Renner'],
              'cotacao': [20, 30, 40, 12, 35]}
dataframe = pd.DataFrame(dicionario)

print(f'''Dataframe sem index personalizado:
      {dataframe}''')
dataframe = dataframe.set_index('empresa')
print(f'''Dataframe com index personalizado:
      {dataframe}''')

Dataframe sem index personalizado:
              empresa  cotacao
0           Weg       20
1     Petrobras       30
2          Vale       40
3     Petrobras       12
4  Lojas Renner       35
Dataframe com index personalizado:
                    cotacao
empresa
Weg                20
Petrobras          30
Vale               40
Petrobras          12
Lojas Renner       35

In [ ]:
#.index cria uma série com um índice personalizado

serie = pd.Series(['Brasil', 'França', 'Australia'], index=['America_do_Sul', 'Europa', 'Oceania'])
print(serie.index)

serie.index[1]

Index(['America_do_Sul', 'Europa', 'Oceania'], dtype='object')

'Europa'

In [ ]:
# reset_index() - reseta o index para o padrão numérico
dataframe = dataframe.reset_index()
dataframe

        empresa  cotacao
0           Weg       20
1     Petrobras       30
2          Vale       40
3     Petrobras       12
4  Lojas Renner       35

In [ ]:
dataframe.index = ['a', 'b', 'c', 'd', 'e']
dataframe

        empresa  cotacao
a           Weg       20
b     Petrobras       30
c          Vale       40
d     Petrobras       12
e  Lojas Renner       35

In [ ]:
#date_range() - cria uma série de datas
datas = pd.date_range(start='2023-01-01', end='2023-01-10')
datas


fim_mes = pd.date_range(start='2023-01-01', end='2023-12-31', freq='ME')
dicionario = {'cotacao': [30, 32, 28, 35, 40, 38, 45, 50, 48, 55, 60, 58]}

cotacao__weg3 = pd.DataFrame(dicionario, index=fim_mes)
cotacao__weg3

            cotacao
2023-01-31       30
2023-02-28       32
2023-03-31       28
2023-04-30       35
2023-05-31       40
2023-06-30       38
2023-07-31       45
2023-08-31       50
2023-09-30       48
2023-10-31       55
2023-11-30       60
2023-12-31       58

In [9]:
cotacao__weg3 = cotacao__weg3[cotacao__weg3.index > '2023-06-30']
cotacao__weg3

NameError: name 'cotacao__weg3' is not defined

In [10]:
#Criando datas com períodos específicos

quatro_dias = pd.date_range(start='2023-01-01', periods=4)
quatro_dias

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04'], dtype='datetime64[ns]', freq='D')

In [11]:
#Desafio 1

carteira = {
    'cotacao': [30, 25, 60, 35],
    'preco_sobre_lucro': [25, 6, 12, 25],
    'volume': [5000, 1000, 4000, 1200],
    'data': pd.date_range(start='2025-08-01', periods=4)
}

df_carteira = pd.DataFrame(carteira)
df_carteira

   cotacao  preco_sobre_lucro  volume       data
0       30                 25    5000 2025-08-01
1       25                  6    1000 2025-08-02
2       60                 12    4000 2025-08-03
3       35                 25    1200 2025-08-04

In [12]:
#Desafio 2
df_carteira = df_carteira.set_index('data')
df_carteira

            cotacao  preco_sobre_lucro  volume
data
2025-08-01       30                 25    5000
2025-08-02       25                  6    1000
2025-08-03       60                 12    4000
2025-08-04       35                 25    1200

In [13]:
#Desafio 3

dicionario = {
    'nomes': ['Weg', 'Petrobras', 'Vale', 'Petrobras', 'Lojas Renner'],
    'tickers': ['WEG3', 'PETR3', 'VALE3', 'PETR4', 'LREN3'],
    'cotacoes': [20, 30, 40, 12, 35],
    'preco_sobre_lucro': [25, 6, 12, 7, 25],
    'volumes': [5000, 1000, 4000, 7000, 1200]
}

df_info_empresas = pd.DataFrame(dicionario)
df_info_empresas = df_info_empresas.set_index('tickers')


df_info_empresas

                nomes  cotacoes  preco_sobre_lucro  volumes
tickers
WEG3              Weg        20                 25     5000
PETR3       Petrobras        30                  6     1000
VALE3            Vale        40                 12     4000
PETR4       Petrobras        12                  7     7000
LREN3    Lojas Renner        35                 25     1200

### Veremos como ordenar e rankear os DataFrames

In [14]:
#Columns - seleciona colunas específicas do DataFrame

df_cambio = pd.DataFrame({
    'moeda': ['Dolar/real', 'Euro/real', 'Libra/real']*2,
    'price': [5.2, 6.1, 7.0, 5.3, 6.2, 7.1],
    'data': sorted(list(pd.date_range(start='01-05-2014', periods=2))*3)})

print(df_cambio)
print('Colunas antes da alteração:', df_cambio.columns)
df_cambio.columns = ['moeda', 'preco', 'data']
print('Colunas depois da alteração:', df_cambio.columns)

        moeda  price       data
0  Dolar/real    5.2 2014-01-05
1   Euro/real    6.1 2014-01-05
2  Libra/real    7.0 2014-01-05
3  Dolar/real    5.3 2014-01-06
4   Euro/real    6.2 2014-01-06
5  Libra/real    7.1 2014-01-06
Colunas antes da alteração: Index(['moeda', 'price', 'data'], dtype='object')
Colunas depois da alteração: Index(['moeda', 'preco', 'data'], dtype='object')

In [15]:
#Selecionar duas colunas específicas
dicionario_dados = {
    'empresas': ['Weg', 'Petrobras', 'Vale', 'Petrobras', 'Lojas Renner'],
    'price': [20, 30, 40, 12, 35],
    'volume': [5000, 1000, 4000, 7000, 1200]
}
df_empresas = pd.DataFrame(dicionario_dados)
df_duas_colunas = df_empresas[['empresas', 'price']]
df_duas_colunas

       empresas  price
0           Weg     20
1     Petrobras     30
2          Vale     40
3     Petrobras     12
4  Lojas Renner     35

In [16]:
#Como selecionar colunas específicas do DataFrame
df_cambio['moeda']


dicionario_dados = {
    'empresas': ['Weg', 'Petrobras', 'Vale', 'Petrobras', 'Lojas Renner'],
    'price': [20, 30, 40, 12, 35],
    'volume': [5000, 1000, 4000, 7000, 1200]
}
df_empresas = pd.DataFrame(dicionario_dados)
coluna1 = df_empresas['empresas']
coluna2 = df_empresas.empresas
print(coluna1)
print(coluna2)
print(type(coluna1))
print(type(coluna2))

0             Weg
1       Petrobras
2            Vale
3       Petrobras
4    Lojas Renner
Name: empresas, dtype: object
0             Weg
1       Petrobras
2            Vale
3       Petrobras
4    Lojas Renner
Name: empresas, dtype: object
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

In [17]:
#Como selecionar uma coluna por condição
print(df_empresas[df_empresas['price'] > 20])
print(df_empresas[df_empresas['empresas'] == 'Petrobras'])
print(df_empresas[df_empresas['empresas'] != 'Petrobras' ])

       empresas  price  volume
1     Petrobras     30    1000
2          Vale     40    4000
4  Lojas Renner     35    1200
    empresas  price  volume
1  Petrobras     30    1000
3  Petrobras     12    7000
       empresas  price  volume
0           Weg     20    5000
2          Vale     40    4000
4  Lojas Renner     35    1200

In [18]:
#Selecionando itens menores que:

dicionario_dados = {
    'empresas': ['Weg', 'Petrobras', 'Vale', 'Petrobras', 'Lojas Renner'],
    'price': [20, 30, 40, 12, 35],
    'volume': [5000, 1000, 4000, 7000, 1200]
}
df_empresas = pd.DataFrame(dicionario_dados)
df_menor = df_empresas[df_empresas['price'] < 20]
df_menor

    empresas  price  volume
3  Petrobras     12    7000

In [19]:
#Selecionando itens iguais a:
df_igual = df_empresas[df_empresas['empresas'] == 'Petrobras']
df_igual

    empresas  price  volume
1  Petrobras     30    1000
3  Petrobras     12    7000

In [20]:
#Como selecionar uma coluna por mais de uma condição
print(df_empresas[(df_empresas['price'] > 20) & (df_empresas['volume'] > 3000)])
print(df_empresas[(df_empresas['price'] > 20) | (df_empresas['volume'] > 3000)])
print(df_empresas[(df_empresas['price'] > 20) & (df_empresas['empresas'] == 'Petrobras')])
print(df_empresas[(df_empresas['price'] < 20) | (df_empresas['empresas'] == 'Petrobras')])

  empresas  price  volume
2     Vale     40    4000
       empresas  price  volume
0           Weg     20    5000
1     Petrobras     30    1000
2          Vale     40    4000
3     Petrobras     12    7000
4  Lojas Renner     35    1200
    empresas  price  volume
1  Petrobras     30    1000
    empresas  price  volume
1  Petrobras     30    1000
3  Petrobras     12    7000

In [21]:
#Selecionando itens com o &:

df_cambio = pd.DataFrame({
    'moeda': ['Dolar/real', 'Euro/real', 'Libra/real']*2,
    'price': [5.2, 6.1, 7.0, 5.3, 6.2, 7.1],
    'data': sorted(list(pd.date_range(start='01-05-2014', periods=3))*2)})

#Dolar com preço maior que 5.2
df_dolar = df_cambio[(df_cambio['moeda'] == 'Dolar/real') & (df_cambio['price'] > 5.0)]
df_dolar

        moeda  price       data
0  Dolar/real    5.2 2014-01-05
3  Dolar/real    5.3 2014-01-06

In [22]:
#Selecionando itens com o |:

df_euro_ou_libra = df_cambio[(df_cambio['moeda'] == 'Euro/real') | (df_cambio['moeda'] == 'Libra/real')]
df_euro_ou_libra

        moeda  price       data
1   Euro/real    6.1 2014-01-05
2  Libra/real    7.0 2014-01-06
4   Euro/real    6.2 2014-01-07
5  Libra/real    7.1 2014-01-07

In [23]:
df_cambio

        moeda  price       data
0  Dolar/real    5.2 2014-01-05
1   Euro/real    6.1 2014-01-05
2  Libra/real    7.0 2014-01-06
3  Dolar/real    5.3 2014-01-06
4   Euro/real    6.2 2014-01-07
5  Libra/real    7.1 2014-01-07

In [24]:
#como selecionar um index específico
df_cambio = df_cambio.set_index('data')
df =df_cambio[(df_cambio.index == '2014-01-05')]
print(df)

                 moeda  price
data
2014-01-05  Dolar/real    5.2
2014-01-05   Euro/real    6.1

In [25]:
#Desafio 1- Selecionar todas as colunas e renomeá-las

df_info_empresas.columns = ['nomes', 'precos', 'preco_sobre_lucro', 'volumes']
df_info_empresas

                nomes  precos  preco_sobre_lucro  volumes
tickers
WEG3              Weg      20                 25     5000
PETR3       Petrobras      30                  6     1000
VALE3            Vale      40                 12     4000
PETR4       Petrobras      12                  7     7000
LREN3    Lojas Renner      35                 25     1200

In [26]:
#Desafio 2- Selecionar a coluna de preços

df_info_empresas_precos = df_info_empresas['precos']
df_info_empresas_precos

tickers
WEG3     20
PETR3    30
VALE3    40
PETR4    12
LREN3    35
Name: precos, dtype: int64

In [27]:
#Desafio 3- Selecionar as duas últimas colunas

df_info_empresas_2_ult = df_info_empresas.iloc[:, -2:]
df_info_empresas_2_ult

         preco_sobre_lucro  volumes
tickers
WEG3                    25     5000
PETR3                    6     1000
VALE3                   12     4000
PETR4                    7     7000
LREN3                   25     1200

In [28]:
#Desafio 4- Selecionar todas as linhas onde o nome da empresa seja Petrobras

df_info_empresas_petrobras = df_info_empresas[df_info_empresas['nomes'] == 'Petrobras']
df_info_empresas_petrobras

             nomes  precos  preco_sobre_lucro  volumes
tickers
PETR3    Petrobras      30                  6     1000
PETR4    Petrobras      12                  7     7000

In [29]:
#Desafio 5 - Selecionar todas as linhas onde o preço sobre lucro seja menor que 20

df_info_empresas_PLmenor20 = df_info_empresas[df_info_empresas['preco_sobre_lucro'] < 20]
df_info_empresas_PLmenor20

             nomes  precos  preco_sobre_lucro  volumes
tickers
PETR3    Petrobras      30                  6     1000
VALE3         Vale      40                 12     4000
PETR4    Petrobras      12                  7     7000

In [30]:
#Desafio 6- Selecionar todas as linhas onde o preço sobre lucro seja maior que 10 e o volume maior que 2000

df_info_empresas_PL10_v2000 = df_info_empresas[(df_info_empresas['preco_sobre_lucro']> 10) & (df_info_empresas['volumes'] > 2000)]
df_info_empresas_PL10_v2000

        nomes  precos  preco_sobre_lucro  volumes
tickers
WEG3      Weg      20                 25     5000
VALE3    Vale      40                 12     4000

In [31]:
#Desafio 7- Selecionar todas as linhas onde o preço seja maior que 20 ou o volume maior que 4000

df_info_empresas_p20_v2000 = df_info_empresas[(df_info_empresas['precos']> 20) | (df_info_empresas['volumes'] > 4000)]
df_info_empresas_p20_v2000

                nomes  precos  preco_sobre_lucro  volumes
tickers
WEG3              Weg      20                 25     5000
PETR3       Petrobras      30                  6     1000
VALE3            Vale      40                 12     4000
PETR4       Petrobras      12                  7     7000
LREN3    Lojas Renner      35                 25     1200

### Propriedades de seleção de dados dentro dos DataFrames

In [71]:
#loc - Seleciona linhas e colunas por rótulo
df_cambio = pd.DataFrame({
    'moeda': ['Dolar/real', 'Libra/real']*4,
    'price': [5.2, 6.1, 7.0, 5.3, 6.2, 7.1, 5.4, 6.3],
    'derivativo': list(['DOLFT3', 'LIBFT3'])*4},
    index = sorted(list(pd.date_range('1/5/2014',periods=4))*2))

df_cambio

                 moeda  price derivativo
2014-01-05  Dolar/real    5.2     DOLFT3
2014-01-05  Libra/real    6.1     LIBFT3
2014-01-06  Dolar/real    7.0     DOLFT3
2014-01-06  Libra/real    5.3     LIBFT3
2014-01-07  Dolar/real    6.2     DOLFT3
2014-01-07  Libra/real    7.1     LIBFT3
2014-01-08  Dolar/real    5.4     DOLFT3
2014-01-08  Libra/real    6.3     LIBFT3

In [72]:
#um unico dia por chave

print(df_cambio.loc['2014-01-05'])

                 moeda  price derivativo
2014-01-05  Dolar/real    5.2     DOLFT3
2014-01-05  Libra/real    6.1     LIBFT3

In [73]:
#selecionar um intervalo

df_cambio.loc['2014-01-05':'2014-01-07']

                 moeda  price derivativo
2014-01-05  Dolar/real    5.2     DOLFT3
2014-01-05  Libra/real    6.1     LIBFT3
2014-01-06  Dolar/real    7.0     DOLFT3
2014-01-06  Libra/real    5.3     LIBFT3
2014-01-07  Dolar/real    6.2     DOLFT3
2014-01-07  Libra/real    7.1     LIBFT3

In [74]:
#Selecionando uma chave e limitando o intervalo da coluna

df_cambio.loc['2014-01-05','moeda':'price']

                 moeda  price
2014-01-05  Dolar/real    5.2
2014-01-05  Libra/real    6.1

In [75]:
#Substituir dados com loc:

df_cambio.loc[df_cambio['derivativo'] == 'DOLFT3', 'derivativo'] = 'DOLFT4'
print(df_cambio)

                 moeda  price derivativo
2014-01-05  Dolar/real    5.2     DOLFT4
2014-01-05  Libra/real    6.1     LIBFT3
2014-01-06  Dolar/real    7.0     DOLFT4
2014-01-06  Libra/real    5.3     LIBFT3
2014-01-07  Dolar/real    6.2     DOLFT4
2014-01-07  Libra/real    7.1     LIBFT3
2014-01-08  Dolar/real    5.4     DOLFT4
2014-01-08  Libra/real    6.3     LIBFT3

In [76]:
#at - Seleciona linhas e colunas por posição

print(df_cambio.at['2014-01-05', 'price'])

2014-01-05    5.2
2014-01-05    6.1
Name: price, dtype: float64

In [77]:
#iloc - Seleciona linhas e colunas por posição
print(df_cambio.iloc[0])

moeda         Dolar/real
price                5.2
derivativo        DOLFT4
Name: 2014-01-05 00:00:00, dtype: object

In [78]:
#intervalo de linhas
print(df_cambio.iloc[0:3])

#intervalo de colunas
print(df_cambio.iloc[:, 0])

#selecionando apenas um item
print(df_cambio.iloc[0, 1])

                 moeda  price derivativo
2014-01-05  Dolar/real    5.2     DOLFT4
2014-01-05  Libra/real    6.1     LIBFT3
2014-01-06  Dolar/real    7.0     DOLFT4
2014-01-05    Dolar/real
2014-01-05    Libra/real
2014-01-06    Dolar/real
2014-01-06    Libra/real
2014-01-07    Dolar/real
2014-01-07    Libra/real
2014-01-08    Dolar/real
2014-01-08    Libra/real
Name: moeda, dtype: object
5.2

In [79]:
#mudando o valor do item

df_cambio.iloc[0,0] = 99 
print(df_cambio.iloc[0])

moeda             99
price            5.2
derivativo    DOLFT4
Name: 2014-01-05 00:00:00, dtype: object

In [80]:
df_cambio

                 moeda  price derivativo
2014-01-05          99    5.2     DOLFT4
2014-01-05  Libra/real    6.1     LIBFT3
2014-01-06  Dolar/real    7.0     DOLFT4
2014-01-06  Libra/real    5.3     LIBFT3
2014-01-07  Dolar/real    6.2     DOLFT4
2014-01-07  Libra/real    7.1     LIBFT3
2014-01-08  Dolar/real    5.4     DOLFT4
2014-01-08  Libra/real    6.3     LIBFT3

In [83]:
#iat Seleciona linhas e colunas por rótulo e posição

print(df_cambio.iat[0,1])

# mudando o valor do item
df_cambio.iat[0,1] = 100
print(df_cambio.iat[0,1])

5.2
100.0

In [84]:
df_info_empresas

                nomes  precos  preco_sobre_lucro  volumes
tickers
WEG3              Weg      20                 25     5000
PETR3       Petrobras      30                  6     1000
VALE3            Vale      40                 12     4000
PETR4       Petrobras      12                  7     7000
LREN3    Lojas Renner      35                 25     1200

In [88]:
# Desafio 1

print(df_info_empresas.loc['WEG3', :])
print(df_info_empresas.loc[:, 'nomes'])

nomes                 Weg
precos                 20
preco_sobre_lucro      25
volumes              5000
Name: WEG3, dtype: object
tickers
WEG3              Weg
PETR3       Petrobras
VALE3            Vale
PETR4       Petrobras
LREN3    Lojas Renner
Name: nomes, dtype: object

In [94]:
# Desafio 2 

print(df_info_empresas.iat[0, 1])

print(df_info_empresas.at['WEG3', 'precos'])

20
20

In [96]:
# Desafio 3 

print(df_info_empresas.iloc[0:2, :])

             nomes  precos  preco_sobre_lucro  volumes
tickers
WEG3           Weg      20                 25     5000
PETR3    Petrobras      30                  6     1000