In [1]:
import os
from dotenv import load_dotenv
import google.generativeai as genai

In [2]:
# Carrecgar variaveis de ambiente do arquivo .env
load_dotenv()

# Acessar a chave da API do Google Generative AI
api_key = os.getenv("GOOGLE_API_KEY")

In [3]:
# Escolher  o modelo

modelos = list(genai.list_models())
for m in modelos:
    print(m.name)

models/embedding-gecko-001
models/gemini-2.5-pro-preview-03-25
models/gemini-2.5-flash-preview-05-20
models/gemini-2.5-flash
models/gemini-2.5-flash-lite-preview-06-17
models/gemini-2.5-pro-preview-05-06
models/gemini-2.5-pro-preview-06-05
models/gemini-2.5-pro
models/gemini-2.0-flash-exp
models/gemini-2.0-flash
models/gemini-2.0-flash-001
models/gemini-2.0-flash-exp-image-generation
models/gemini-2.0-flash-lite-001
models/gemini-2.0-flash-lite
models/gemini-2.0-flash-preview-image-generation
models/gemini-2.0-flash-lite-preview-02-05
models/gemini-2.0-flash-lite-preview
models/gemini-2.0-pro-exp
models/gemini-2.0-pro-exp-02-05
models/gemini-exp-1206
models/gemini-2.0-flash-thinking-exp-01-21
models/gemini-2.0-flash-thinking-exp
models/gemini-2.0-flash-thinking-exp-1219
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/learnlm-2.0-flash-experimental
models/gemma-3-1b-it
models/gemma-3-4b-it
models/gemma-3-12b-it
models/gemma-3-27b-it
models/gemma-3n-e4b-it
models/gemma-3n-e2b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image-preview
models/gemini-2.5-flash-image
models/gemini-2.5-flash-preview-09-2025
models/gemini-2.5-flash-lite-preview-09-2025
models/gemini-robotics-er-1.5-preview
models/gemini-2.5-computer-use-preview-10-2025
models/embedding-001
models/text-embedding-004
models/gemini-embedding-exp-03-07
models/gemini-embedding-exp
models/gemini-embedding-001
models/aqa
models/imagen-4.0-generate-preview-06-06
models/imagen-4.0-ultra-generate-preview-06-06
models/imagen-4.0-generate-001
models/imagen-4.0-ultra-generate-001
models/imagen-4.0-fast-generate-001
models/veo-2.0-generate-001
models/veo-3.0-generate-preview
models/veo-3.0-fast-generate-preview
models/veo-3.0-generate-001
models/veo-3.0-fast-generate-001
models/veo-3.1-generate-preview
models/veo-3.1-fast-generate-preview
models/gemini-2.0-flash-live-001
models/gemini-live-2.5-flash-preview
models/gemini-2.5-flash-live-preview
models/gemini-2.5-flash-native-audio-latest
models/gemini-2.5-flash-native-audio-preview-09-2025

In [4]:


# Configurar a chave da API
genai.configure(api_key=api_key)

# Fazer uma solicitação ao modelo de linguagem
model = genai.GenerativeModel('gemini-2.5-flash')
response = model.generate_content(
    "Explique o que é inteligência artificial de forma simples.")

print(response.text)

ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 10
Please retry in 41.117347207s. [links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 10
}
, retry_delay {
  seconds: 41
}
]

In [5]:
# Criar um chat (sessão de conversa)
chat = model.start_chat(history=[])

# Enviar mensagem
response = chat.send_message("Explique o que é inteligência artificial de forma simples.")

# Mostrar resposta
print(response.text)

ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 10
Please retry in 29.111199969s. [links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 10
}
, retry_delay {
  seconds: 29
}
]

In [7]:
# Enviar mensagem
response = chat.send_message("Quando foi lançado o ChatGPT?")

# Mostrar resposta
print(response.text)

O ChatGPT foi lançado ao público em **30 de novembro de 2022**.

Essa data marca o lançamento da versão inicial do chatbot conversacional da OpenAI, que rapidamente ganhou enorme popularidade global.

In [8]:
# 🔁 Ver histórico da conversa
print("\n=== Histórico da conversa ===")
for msg in chat.history:
    print(f"{msg.role}: {msg.parts[0].text}")

=== Histórico da conversa ===
user: Explique o que é inteligência artificial de forma simples.
model: Imagine que você está ensinando um computador a "pensar" e a "aprender" como um ser humano faria.

**Inteligência Artificial (IA) de forma simples:**

É a área da computação que tenta fazer com que máquinas e softwares consigam realizar tarefas que normalmente exigem **inteligência humana**.

Isso inclui coisas como:

1.  **Aprender:** Analisar dados e identificar padrões, melhorando com a experiência (como um humano que pratica algo e fica melhor).
2.  **Raciocinar e Resolver Problemas:** Tomar decisões lógicas ou encontrar soluções para desafios (como jogar xadrez ou resolver um quebra-cabeça).
3.  **Entender a Linguagem Humana:** Interpretar o que você fala ou escreve (como a Siri, a Alexa ou o Google Tradutor).
4.  **Reconhecer Padrões:** Identificar rostos em fotos, objetos em vídeos, ou anomalias em dados (como um sistema de segurança que detecta fraudes).
5.  **Criar:** Gerar textos, imagens, músicas ou até códigos de programação.

**Como ela faz isso?**

Basicamente, através de programas de computador (chamados **algoritmos**) que são "treinados" com uma quantidade enorme de dados. Por exemplo, para um computador reconhecer um gato, você mostra a ele milhares de fotos de gatos e não-gatos, e ele aprende a identificar as características que definem um gato.

**Em resumo:**

Pense na IA como **uma ferramenta superinteligente, criada pelo homem, que consegue imitar e até superar algumas capacidades do cérebro humano em tarefas específicas**, aprendendo e se adaptando para nos servir melhor.
user: Quando foi lançado o ChatGPT?
model: O ChatGPT foi lançado ao público em **30 de novembro de 2022**.

Essa data marca o lançamento da versão inicial do chatbot conversacional da OpenAI, que rapidamente ganhou enorme popularidade global.

In [9]:
# Enviar mensagem
response = chat.send_message("Quais as principais diferenças entre o ChatGPT e o Gemini?")

# Mostrar resposta
print(response.text)

ChatGPT e Gemini são dois dos mais proeminentes modelos de inteligência artificial generativa conversacional (chatbots) atualmente, mas eles vêm de desenvolvedores diferentes e possuem algumas distinções importantes em sua arquitetura, capacidades e integração.

Aqui estão as principais diferenças:

1.  **Desenvolvedor:**
    *   **ChatGPT:** Desenvolvido pela **OpenAI**.
    *   **Gemini:** Desenvolvido pela **Google**.

2.  **Modelos Subjacentes:**
    *   **ChatGPT:** Baseia-se na família de modelos **GPT** (Generative Pre-trained Transformer), sendo as versões mais recentes o GPT-3.5 (gratuito) e o GPT-4 (versão paga do ChatGPT Plus e Enterprise).
    *   **Gemini:** Baseia-se na família de modelos **Gemini**, que foi introduzida como sucessora do modelo LaMDA (que alimentava o Bard, o antecessor do Gemini). Há diferentes tamanhos: Nano (para dispositivos), Pro (versão gratuita e paga) e Ultra (a versão mais potente, parte do plano Gemini Advanced).

3.  **Data de Lançamento e Evolução:**
    *   **ChatGPT:** Lançado ao público em **novembro de 2022**. Foi o chatbot que popularizou enormemente a IA generativa.
    *   **Gemini:** Originalmente lançado como "Bard" em **março de 2023**. Em **fevereiro de 2024**, o Bard foi oficialmente renomeado para "Gemini" e passou a usar os modelos Gemini diretamente, incluindo a versão Ultra na assinatura "Gemini Advanced".

4.  **Multimodalidade (Principal Diferença Conceitual):**
    *   **ChatGPT:** Embora as versões mais recentes do ChatGPT (com GPT-4) tenham ganhado capacidades multimodais (como entrada de imagem, voz e geração de imagens via DALL-E 3), elas foram adicionadas como **integrações ou extensões**. O modelo original GPT-3.5 era primariamente focado em texto.
    *   **Gemini:** Foi **projetado e treinado desde o início para ser multimodal de forma nativa**. Isso significa que ele foi criado para entender e operar perfeitamente com diferentes tipos de informação – texto, imagens, áudio e vídeo – de uma maneira mais integrada e simultânea. A ideia é que ele possa "raciocinar" sobre essas diferentes modalidades juntas.

5.  **Integração com Ecossistemas:**
    *   **ChatGPT:** Possui uma API robusta para integração com diversas ferramentas de terceiros e plugins. A OpenAI também oferece produtos como DALL-E (geração de imagem) e Sora (geração de vídeo).
    *   **Gemini:** Tem uma integração mais profunda com o **ecossistema Google**. Isso inclui acesso em tempo real à Busca do Google para informações atualizadas, integração com o Google Workspace (Gmail, Docs, Planilhas) para sumarização ou criação de conteúdo, e potencial conexão com outros serviços Google como YouTube e Android.

6.  **Desempenho e Capacidades (Geral):**
    *   **ChatGPT (especialmente GPT-4):** É frequentemente elogiado pela sua fluidez na geração de texto, criatividade, nuance na compreensão de linguagem complexa, e fortes capacidades de raciocínio para diversas tarefas, incluindo programação.
    *   **Gemini (especialmente Ultra):** A Google o destaca por suas capacidades avançadas em raciocínio lógico, matemática, programação e, claro, seu entendimento multimodal. A integração com a Busca do Google lhe dá uma vantagem para informações em tempo real e fatuais.

7.  **"Personalidade" e Estilo:**
    *   **ChatGPT:** Muitos usuários o descrevem como mais "neutro" ou "formal" no tom, embora possa ser adaptado.
    *   **Gemini:** Herdando um pouco do Bard, pode ser percebido como um pouco mais "conversacional", "ousado" ou até com um toque de humor, embora isso também possa ser ajustado.

Em resumo, enquanto ambos são ferramentas incrivelmente poderosas para comunicação e geração de conteúdo, a **multimodalidade nativa do Gemini e sua profunda integração com o ecossistema Google** são as principais distinções técnicas e de uso em relação ao ChatGPT, que popularizou a conversa por IA e tem uma forte base em modelos de linguagem avançados. Ambos estão em rápida evolução, e suas capacidades continuam a se expandir e a se sobrepor em muitas áreas.

In [10]:
# 🔁 Ver histórico da conversa
print("\n=== Histórico da conversa ===")
for msg in chat.history:
    print(f"{msg.role}: {msg.parts[0].text}")

=== Histórico da conversa ===
user: Explique o que é inteligência artificial de forma simples.
model: Imagine que você está ensinando um computador a "pensar" e a "aprender" como um ser humano faria.

**Inteligência Artificial (IA) de forma simples:**

É a área da computação que tenta fazer com que máquinas e softwares consigam realizar tarefas que normalmente exigem **inteligência humana**.

Isso inclui coisas como:

1.  **Aprender:** Analisar dados e identificar padrões, melhorando com a experiência (como um humano que pratica algo e fica melhor).
2.  **Raciocinar e Resolver Problemas:** Tomar decisões lógicas ou encontrar soluções para desafios (como jogar xadrez ou resolver um quebra-cabeça).
3.  **Entender a Linguagem Humana:** Interpretar o que você fala ou escreve (como a Siri, a Alexa ou o Google Tradutor).
4.  **Reconhecer Padrões:** Identificar rostos em fotos, objetos em vídeos, ou anomalias em dados (como um sistema de segurança que detecta fraudes).
5.  **Criar:** Gerar textos, imagens, músicas ou até códigos de programação.

**Como ela faz isso?**

Basicamente, através de programas de computador (chamados **algoritmos**) que são "treinados" com uma quantidade enorme de dados. Por exemplo, para um computador reconhecer um gato, você mostra a ele milhares de fotos de gatos e não-gatos, e ele aprende a identificar as características que definem um gato.

**Em resumo:**

Pense na IA como **uma ferramenta superinteligente, criada pelo homem, que consegue imitar e até superar algumas capacidades do cérebro humano em tarefas específicas**, aprendendo e se adaptando para nos servir melhor.
user: Quando foi lançado o ChatGPT?
model: O ChatGPT foi lançado ao público em **30 de novembro de 2022**.

Essa data marca o lançamento da versão inicial do chatbot conversacional da OpenAI, que rapidamente ganhou enorme popularidade global.
user: Quais as principais diferenças entre o ChatGPT e o Gemini?
model: ChatGPT e Gemini são dois dos mais proeminentes modelos de inteligência artificial generativa conversacional (chatbots) atualmente, mas eles vêm de desenvolvedores diferentes e possuem algumas distinções importantes em sua arquitetura, capacidades e integração.

Aqui estão as principais diferenças:

1.  **Desenvolvedor:**
    *   **ChatGPT:** Desenvolvido pela **OpenAI**.
    *   **Gemini:** Desenvolvido pela **Google**.

2.  **Modelos Subjacentes:**
    *   **ChatGPT:** Baseia-se na família de modelos **GPT** (Generative Pre-trained Transformer), sendo as versões mais recentes o GPT-3.5 (gratuito) e o GPT-4 (versão paga do ChatGPT Plus e Enterprise).
    *   **Gemini:** Baseia-se na família de modelos **Gemini**, que foi introduzida como sucessora do modelo LaMDA (que alimentava o Bard, o antecessor do Gemini). Há diferentes tamanhos: Nano (para dispositivos), Pro (versão gratuita e paga) e Ultra (a versão mais potente, parte do plano Gemini Advanced).

3.  **Data de Lançamento e Evolução:**
    *   **ChatGPT:** Lançado ao público em **novembro de 2022**. Foi o chatbot que popularizou enormemente a IA generativa.
    *   **Gemini:** Originalmente lançado como "Bard" em **março de 2023**. Em **fevereiro de 2024**, o Bard foi oficialmente renomeado para "Gemini" e passou a usar os modelos Gemini diretamente, incluindo a versão Ultra na assinatura "Gemini Advanced".

4.  **Multimodalidade (Principal Diferença Conceitual):**
    *   **ChatGPT:** Embora as versões mais recentes do ChatGPT (com GPT-4) tenham ganhado capacidades multimodais (como entrada de imagem, voz e geração de imagens via DALL-E 3), elas foram adicionadas como **integrações ou extensões**. O modelo original GPT-3.5 era primariamente focado em texto.
    *   **Gemini:** Foi **projetado e treinado desde o início para ser multimodal de forma nativa**. Isso significa que ele foi criado para entender e operar perfeitamente com diferentes tipos de informação – texto, imagens, áudio e vídeo – de uma maneira mais integrada e simultânea. A ideia é que ele possa "raciocinar" sobre essas diferentes modalidades juntas.

5.  **Integração com Ecossistemas:**
    *   **ChatGPT:** Possui uma API robusta para integração com diversas ferramentas de terceiros e plugins. A OpenAI também oferece produtos como DALL-E (geração de imagem) e Sora (geração de vídeo).
    *   **Gemini:** Tem uma integração mais profunda com o **ecossistema Google**. Isso inclui acesso em tempo real à Busca do Google para informações atualizadas, integração com o Google Workspace (Gmail, Docs, Planilhas) para sumarização ou criação de conteúdo, e potencial conexão com outros serviços Google como YouTube e Android.

6.  **Desempenho e Capacidades (Geral):**
    *   **ChatGPT (especialmente GPT-4):** É frequentemente elogiado pela sua fluidez na geração de texto, criatividade, nuance na compreensão de linguagem complexa, e fortes capacidades de raciocínio para diversas tarefas, incluindo programação.
    *   **Gemini (especialmente Ultra):** A Google o destaca por suas capacidades avançadas em raciocínio lógico, matemática, programação e, claro, seu entendimento multimodal. A integração com a Busca do Google lhe dá uma vantagem para informações em tempo real e fatuais.

7.  **"Personalidade" e Estilo:**
    *   **ChatGPT:** Muitos usuários o descrevem como mais "neutro" ou "formal" no tom, embora possa ser adaptado.
    *   **Gemini:** Herdando um pouco do Bard, pode ser percebido como um pouco mais "conversacional", "ousado" ou até com um toque de humor, embora isso também possa ser ajustado.

Em resumo, enquanto ambos são ferramentas incrivelmente poderosas para comunicação e geração de conteúdo, a **multimodalidade nativa do Gemini e sua profunda integração com o ecossistema Google** são as principais distinções técnicas e de uso em relação ao ChatGPT, que popularizou a conversa por IA e tem uma forte base em modelos de linguagem avançados. Ambos estão em rápida evolução, e suas capacidades continuam a se expandir e a se sobrepor em muitas áreas.

In [11]:
prompt = input("Digite sua pergunta: ")

while prompt != 'fim':
    response = chat.send_message(prompt)
    print(prompt)
    print("Resposta:", response.text)
    print("\n")
    prompt = input("Digite sua pergunta: ")

In [12]:
# Desafio

lista_de_nomes = ["Ana", "Bruno", "Carla", "Daniel", "Eduardo", "Fernanda", "Gabriel", "Helena"]
lista_de_medias = [8.5, 7.0, 1.0, 3.5, 2.0, 7.5, 9.5, 9.5]

for nome, media in zip(lista_de_nomes, lista_de_medias):
    if media >= 7.0:
        status = "Aprovado"
    elif 4.0 <= media < 7.0:
        status = "Recuperação"
    else:
        status = "Reprovado"
    print(f"Aluno: {nome}, Média: {media}, Status: {status}")

Aluno: Ana, Média: 8.5, Status: Aprovado
Aluno: Bruno, Média: 7.0, Status: Aprovado
Aluno: Carla, Média: 1.0, Status: Reprovado
Aluno: Daniel, Média: 3.5, Status: Reprovado
Aluno: Eduardo, Média: 2.0, Status: Reprovado
Aluno: Fernanda, Média: 7.5, Status: Aprovado
Aluno: Gabriel, Média: 9.5, Status: Aprovado
Aluno: Helena, Média: 9.5, Status: Aprovado

In [13]:
for nome, media in zip(lista_de_nomes, lista_de_medias):
    media += 1.0  # Bônus de 1 ponto para todos os alunos
    if media > 10.0:
        media = 10.0  # Limitar a média máxima a 10.0
    if media >= 7.0:
        status = "Aprovado"
    elif 4.0 <= media < 7.0:
        status = "Recuperação"
    else:
        status = "Reprovado"
    print(f"Aluno: {nome}, Média com bônus: {media}, Status: {status}")

Aluno: Ana, Média com bônus: 9.5, Status: Aprovado
Aluno: Bruno, Média com bônus: 8.0, Status: Aprovado
Aluno: Carla, Média com bônus: 2.0, Status: Reprovado
Aluno: Daniel, Média com bônus: 4.5, Status: Recuperação
Aluno: Eduardo, Média com bônus: 3.0, Status: Reprovado
Aluno: Fernanda, Média com bônus: 8.5, Status: Aprovado
Aluno: Gabriel, Média com bônus: 10.0, Status: Aprovado
Aluno: Helena, Média com bônus: 10.0, Status: Aprovado

In [14]:
n = 0

while n < len(lista_de_medias):
    lista_de_medias[n] = lista_de_medias[n] + 1.0
    if lista_de_medias[n] > 10.0:
        lista_de_medias[n] = 10.0
    n += 1

print(lista_de_medias)

[9.5, 8.0, 2.0, 4.5, 3.0, 8.5, 10.0, 10.0]

In [15]:
lista_de_nomes.append("Isabela")

print(lista_de_nomes)

['Ana', 'Bruno', 'Carla', 'Daniel', 'Eduardo', 'Fernanda', 'Gabriel', 'Helena', 'Isabela']

In [16]:
lista_de_nomes.extend(["Isabela", "João", "Mariana"])
print(lista_de_nomes)

['Ana', 'Bruno', 'Carla', 'Daniel', 'Eduardo', 'Fernanda', 'Gabriel', 'Helena', 'Isabela', 'Isabela', 'João', 'Mariana']

In [17]:
dicionario_de_alunos = {}
for nome, media in zip(lista_de_nomes, lista_de_medias):
    dicionario_de_alunos[nome] = media 
print(dicionario_de_alunos)

{'Ana': 9.5, 'Bruno': 8.0, 'Carla': 2.0, 'Daniel': 4.5, 'Eduardo': 3.0, 'Fernanda': 8.5, 'Gabriel': 10.0, 'Helena': 10.0}

In [18]:
dicionario_de_alunos.get("Ana")

9.5

In [19]:
dict_desafio = [
    {'nome': 'Ana', 'media': 8.5, 'status': 'Aprovado'},
    {'nome': 'Bruno', 'media': 7.0, 'status': 'Aprovado'},
    {'nome': 'Carla', 'media': 1.0, 'status': 'Reprovado'},
    {'nome': 'Daniel', 'media': 3.5, 'status': 'Reprovado'},
    {'nome': 'Eduardo', 'media': 2.0, 'status': 'Reprovado'},
    {'nome': 'Fernanda', 'media': 7.5, 'status': 'Aprovado'},
    {'nome': 'Gabriel', 'media': 9.5, 'status': 'Aprovado'},
    {'nome': 'Helena', 'media': 9.5, 'status': 'Aprovado'}         
]

In [20]:
dict_desafio[0]

{'nome': 'Ana', 'media': 8.5, 'status': 'Aprovado'}

In [21]:
dict_desafio[0]['media']

8.5

In [22]:
n = 0
while n < len(dict_desafio):
    print(dict_desafio[n])
    n += 1

{'nome': 'Ana', 'media': 8.5, 'status': 'Aprovado'}
{'nome': 'Bruno', 'media': 7.0, 'status': 'Aprovado'}
{'nome': 'Carla', 'media': 1.0, 'status': 'Reprovado'}
{'nome': 'Daniel', 'media': 3.5, 'status': 'Reprovado'}
{'nome': 'Eduardo', 'media': 2.0, 'status': 'Reprovado'}
{'nome': 'Fernanda', 'media': 7.5, 'status': 'Aprovado'}
{'nome': 'Gabriel', 'media': 9.5, 'status': 'Aprovado'}
{'nome': 'Helena', 'media': 9.5, 'status': 'Aprovado'}

In [23]:
for element in dict_desafio:
    print(element)

{'nome': 'Ana', 'media': 8.5, 'status': 'Aprovado'}
{'nome': 'Bruno', 'media': 7.0, 'status': 'Aprovado'}
{'nome': 'Carla', 'media': 1.0, 'status': 'Reprovado'}
{'nome': 'Daniel', 'media': 3.5, 'status': 'Reprovado'}
{'nome': 'Eduardo', 'media': 2.0, 'status': 'Reprovado'}
{'nome': 'Fernanda', 'media': 7.5, 'status': 'Aprovado'}
{'nome': 'Gabriel', 'media': 9.5, 'status': 'Aprovado'}
{'nome': 'Helena', 'media': 9.5, 'status': 'Aprovado'}

In [24]:
texto2 = " Joao  da Silva    Gonçalves     "      # João da Silva Gonçalves (bagunçado)
texto3 = "Mar eraL uz anes So"        # Maria Luz Soares (bagunçado)
texto4 = "Pe&dro  Mgiuel  Rtocha"     # Pedro Miguel Rocha (bagunçado)
texto5 = "An  Ca rloP at ric ia"      # Ana Carolina Patrícia (bagunçado)
texto6 = "Lu!iz Fe rnand  Coesrta"    # Luiz Fernando Costa (bagunçado)

In [25]:
def limpar_texto(texto):
    texto_limpo = texto.upper().split()
    texto_limpo = " ".join(texto_limpo)
    return texto_limpo

In [26]:
limpar_texto(texto2)

'JOAO DA SILVA GONÇALVES'

In [27]:
def limpar_texto(texto):
    print(" ".join(texto.upper().split()))

limpar_texto(texto2)

JOAO DA SILVA GONÇALVES

In [28]:
salas_de_aula = ['sala1', 'sala2', 'sala3']

In [29]:
import random

def aloca_alunos_em_salas(nome_dos_alunos, listas_de_salas):
    sala_do_aluno = random.choice(listas_de_salas)
    
    dict_aluno = {
        'nome': nome_dos_alunos,
        'sala': sala_do_aluno
    }
    print(dict_aluno)

In [30]:
nome_limpo = limpar_texto(texto2)
aloca_alunos_em_salas(nome_limpo, salas_de_aula)

JOAO DA SILVA GONÇALVES
{'nome': None, 'sala': 'sala2'}

In [31]:
emails = [
    """Assunto: Reunião de alinhamento do projeto  
Olá equipe,  
Gostaria de confirmar nossa reunião de alinhamento amanhã às 10h.  
Por favor, tragam as atualizações das suas tarefas.  
Atenciosamente,  
Mariana Souza""",

    """Assunto: Oferta especial de fim de semana  
Aproveite descontos de até 70% em eletrônicos e móveis!  
Promoção válida até domingo.  
Equipe LojaOnline""",

    """Assunto: Alerta de segurança  
Detectamos um novo acesso à sua conta a partir de um dispositivo desconhecido.  
Se não foi você, altere sua senha imediatamente.  
Suporte Técnico""",

    """Assunto: Convite para o casamento  
Com grande alegria convidamos você para o casamento de Ana e Lucas,  
que acontecerá no dia 12 de dezembro, às 17h.  
Esperamos por você!""",

    """Assunto: Confirmação de reserva  
Sua reserva no Hotel Paraíso foi confirmada.  
Check-in: 23/11 | Check-out: 27/11.  
Tenha uma ótima estadia!""",

    """Assunto: Atualização de entrega  
Seu pedido #458732 está a caminho!  
Previsão de chegada: terça-feira, 14h às 18h.  
Equipe de Logística"""

#     """Assunto: Resultado da seleção  
# Parabéns! Você foi aprovado para a próxima etapa do processo seletivo.  
# Entraremos em contato para agendar a entrevista.  
# RH - Empresa Futuro""",

#     """Assunto: Lembrete de pagamento  
# Sua fatura vence amanhã, 11/11.  
# Evite juros e multas efetuando o pagamento em dia.  
# Financeiro - Banco Solidez""",

#     """Assunto: Atualização de política de privacidade  
# Estamos atualizando nossos termos de uso para oferecer mais transparência.  
# Confira as mudanças em nosso site.""",

#     """Assunto: Convite para o evento de tecnologia  
# Participe da TechWeek 2025 — palestras, workshops e networking.  
# Inscreva-se gratuitamente até 15/12!""",

#     """Assunto: Agradecimento pela compra  
# Olá João,  
# Agradecemos por adquirir nossos produtos.  
# Seu feedback é muito importante para nós!""",

#     """Assunto: Comunicado importante aos colaboradores  
# Prezados,  
# Informamos que o expediente de sexta-feira será encerrado às 14h devido à manutenção elétrica.""",

#     """Assunto: Aviso de manutenção programada  
# O sistema ficará indisponível das 22h às 02h para melhorias de desempenho.  
# Pedimos desculpas por qualquer inconveniente.""",

#     """Assunto: Promoção exclusiva para clientes premium  
# Ganhe 20% de desconto em sua próxima compra usando o código PREMIUM20!""",

#     """Assunto: Confirmação de inscrição  
# Sua inscrição no curso “Python para Iniciantes” foi confirmada.  
# As aulas começam em 02/12.""",

#     """Assunto: Reunião cancelada  
# A reunião de status semanal foi cancelada.  
# Enviaremos uma nova data em breve.""",

#     """Assunto: Relatório mensal  
# Segue anexo o relatório de desempenho do mês de outubro.  
# Qualquer dúvida, fico à disposição.""",

#     """Assunto: Pedido de suporte  
# Bom dia,  
# Estou enfrentando dificuldades para acessar minha conta.  
# Podem me ajudar?  
# Grato,  
# Carlos""",

#     """Assunto: Feliz aniversário!  
# Toda a equipe deseja a você um dia repleto de alegrias e realizações.  
# Parabéns!""",

#     """Assunto: Newsletter de novembro  
# Confira as novidades, dicas e oportunidades que preparamos para você neste mês!  
# Equipe ConectaNews"""
]

# Exibe os 20 emails gerados
for i, email in enumerate(emails, start=1):
    print(f"--- Email {i} ---\n{email}\n")

--- Email 1 ---
Assunto: Reunião de alinhamento do projeto
Olá equipe,
Gostaria de confirmar nossa reunião de alinhamento amanhã às 10h.
Por favor, tragam as atualizações das suas tarefas.
Atenciosamente,
Mariana Souza

--- Email 2 ---
Assunto: Oferta especial de fim de semana
Aproveite descontos de até 70% em eletrônicos e móveis!
Promoção válida até domingo.
Equipe LojaOnline

--- Email 3 ---
Assunto: Alerta de segurança
Detectamos um novo acesso à sua conta a partir de um dispositivo desconhecido.
Se não foi você, altere sua senha imediatamente.
Suporte Técnico

--- Email 4 ---
Assunto: Convite para o casamento
Com grande alegria convidamos você para o casamento de Ana e Lucas,
que acontecerá no dia 12 de dezembro, às 17h.
Esperamos por você!

--- Email 5 ---
Assunto: Confirmação de reserva
Sua reserva no Hotel Paraíso foi confirmada.
Check-in: 23/11 | Check-out: 27/11.
Tenha uma ótima estadia!

--- Email 6 ---
Assunto: Atualização de entrega
Seu pedido #458732 está a caminho!
Previsão de chegada: terça-feira, 14h às 18h.
Equipe de Logística

In [32]:
def resumo(emails):
    response = chat.send_message(f'Resuma o {emails} em apenas uma linha, definindo o que essa pessoa queria no email')
    print("Resposta:", response.text)

In [33]:
resumo(emails)

Resposta: A remetente, Mariana Souza, queria confirmar a reunião de alinhamento do projeto e que a equipe trouxesse as atualizações das tarefas.

In [34]:
def resumo(emails):
    lista_de_resumos = []

    for numero, email in enumerate(emails):
        response = model.generate_content(f"""Vou te mandar o corpo de um email. 
            Qual é o resumo em apenas uma linha, 
            passando o que essa pessoa queria no email, segue o email: {email}""")
        print(f"Email {numero + 1}:", response.text)
        lista_de_resumos.append(f'E-mail {numero + 1}: {response.text}')
        print("-" * 50)
    
    return lista_de_resumos

In [35]:
lista_de_resumos = resumo(emails)

Email 1: Mariana confirma a reunião de alinhamento de amanhã às 10h e pede que todos tragam as atualizações de suas tarefas.
--------------------------------------------------
Email 2: A LojaOnline quer que você aproveite descontos de até 70% em eletrônicos e móveis neste fim de semana, válidos até domingo.
--------------------------------------------------
Email 3: O Suporte Técnico alerta sobre um novo acesso desconhecido à sua conta e solicita que você altere sua senha imediatamente caso não o reconheça.
--------------------------------------------------
Email 4: A pessoa queria convidar para o casamento de Ana e Lucas no dia 12 de dezembro às 17h.
--------------------------------------------------
Email 5: Este email é uma **confirmação da sua reserva no Hotel Paraíso**, com check-in em 23/11 e check-out em 27/11.
--------------------------------------------------
Email 6: A Equipe de Logística queria informar que seu pedido #458732 está a caminho e a previsão de chegada é terça-feira, das 14h às 18h.
--------------------------------------------------

In [36]:
lista_de_resumos

['E-mail 1: Mariana confirma a reunião de alinhamento de amanhã às 10h e pede que todos tragam as atualizações de suas tarefas.',
 'E-mail 2: A LojaOnline quer que você aproveite descontos de até 70% em eletrônicos e móveis neste fim de semana, válidos até domingo.',
 'E-mail 3: O Suporte Técnico alerta sobre um novo acesso desconhecido à sua conta e solicita que você altere sua senha imediatamente caso não o reconheça.',
 'E-mail 4: A pessoa queria convidar para o casamento de Ana e Lucas no dia 12 de dezembro às 17h.',
 'E-mail 5: Este email é uma **confirmação da sua reserva no Hotel Paraíso**, com check-in em 23/11 e check-out em 27/11.',
 'E-mail 6: A Equipe de Logística queria informar que seu pedido #458732 está a caminho e a previsão de chegada é terça-feira, das 14h às 18h.']

In [37]:
from groq import Groq

# Carrega as variáveis do arquivo .env
load_dotenv()

# Acessar a chave da API do Groq
api_key = os.getenv("GROQ_API_KEY")

client = Groq(api_key=api_key)
completion = client.chat.completions.create(
    model="openai/gpt-oss-20b",
    messages=[
      {
        "role": "user",
        "content": "O que é ia?"
      }
    ],
    temperature=1, #0- é o menos criativo possível e 2- é o mais criativo possivel
    max_completion_tokens=8192,
    top_p=1,
    reasoning_effort="medium",
    stream=True,
    stop=None
)

for chunk in completion:
    print(chunk.choices[0].delta.content or "", end="")

**IA** é a sigla para **Inteligência Artificial**.
Em termos gerais, Inteligência Artificial é a área da ciência da computação que se dedica a criar sistemas (algoritmos, programas, dispositivos) capazes de executar tarefas que normalmente requereriam inteligência humana. Essas tarefas incluem:

| Área | Exemplos de aplicação |
|------|-----------------------|
| **Aprendizado de máquina** | Reconhecimento de imagens, previsão de demanda, detecção de fraude |
| **Processamento de linguagem natural (PLN)** | Assistentes virtuais (ex.: Siri, Alexa), tradução automática, análise de sentimentos |
| **Robótica** | Robôs industriais, veículos autônomos, drones |
| **Sistemas especialistas** | Diagnósticos médicos, recomendação de produtos |
| **Jogos e simulação** | Jogadores de xadrez, jogos de estratégia, simulações de realidade virtual |

### Como funciona?

1. **Coleta de dados** – O sistema aprende a partir de grandes quantidades de informação (imagens, textos, sensores, etc.).
2. **Treinamento** – Usando algoritmos de aprendizado (por exemplo, redes neurais profundas), o modelo ajusta parâmetros internos para reconhecer padrões ou tomar decisões.
3. **Inferência** – Depois de treinado, o modelo aplica o que aprendeu a novos dados, produzindo resultados (classificação, predição, recomendação).

### Por que é importante?

- **Automação** de processos repetitivos e intensivos.
- **Aumento de eficiência** em setores como saúde, finanças, logística e manufatura.
- **Acesso a insights** a partir de grandes volumes de dados que seriam impossíveis de analisar manualmente.

### Considerações éticas e sociais

- **Privacidade** – Proteção dos dados usados para treinar modelos.
- **Viés** – Garantir que os modelos não perpetuem preconceitos presentes nos dados.
- **Responsabilidade** – Determinar quem é responsável por decisões automatizadas.

---

Se quiser saber mais detalhes sobre algum tipo específico de IA (por exemplo, redes neurais, aprendizado profundo, visão computacional, etc.) ou tiver alguma pergunta mais específica, é só dizer!

### Lendo e escrevendo em arquivos usando Python

In [38]:
with open('lista_de_resumos.txt', 'w', encoding='utf-8') as arquivo:
    for resumo in lista_de_resumos:
        arquivo.write(resumo + '\n')

In [39]:
print(os.getcwd())

/home/jgonsan/Documents/dev/github/Python

In [40]:
nova_lista_de_resumos = []
with open('lista_de_resumos.txt', 'r', encoding='utf-8') as arquivo:
    for linha in arquivo:
       nova_lista_de_resumos.append(linha.strip())

In [41]:
nova_lista_de_resumos

['E-mail 1: Mariana confirma a reunião de alinhamento de amanhã às 10h e pede que todos tragam as atualizações de suas tarefas.',
 'E-mail 2: A LojaOnline quer que você aproveite descontos de até 70% em eletrônicos e móveis neste fim de semana, válidos até domingo.',
 'E-mail 3: O Suporte Técnico alerta sobre um novo acesso desconhecido à sua conta e solicita que você altere sua senha imediatamente caso não o reconheça.',
 'E-mail 4: A pessoa queria convidar para o casamento de Ana e Lucas no dia 12 de dezembro às 17h.',
 'E-mail 5: Este email é uma **confirmação da sua reserva no Hotel Paraíso**, com check-in em 23/11 e check-out em 27/11.',
 'E-mail 6: A Equipe de Logística queria informar que seu pedido #458732 está a caminho e a previsão de chegada é terça-feira, das 14h às 18h.']

In [42]:
conteudo = ""
with open('lista_de_resumos.txt', 'r', encoding='utf-8') as arquivo:
    conteudo = arquivo.read()

In [43]:
conteudo

'E-mail 1: Mariana confirma a reunião de alinhamento de amanhã às 10h e pede que todos tragam as atualizações de suas tarefas.\nE-mail 2: A LojaOnline quer que você aproveite descontos de até 70% em eletrônicos e móveis neste fim de semana, válidos até domingo.\nE-mail 3: O Suporte Técnico alerta sobre um novo acesso desconhecido à sua conta e solicita que você altere sua senha imediatamente caso não o reconheça.\nE-mail 4: A pessoa queria convidar para o casamento de Ana e Lucas no dia 12 de dezembro às 17h.\nE-mail 5: Este email é uma **confirmação da sua reserva no Hotel Paraíso**, com check-in em 23/11 e check-out em 27/11.\nE-mail 6: A Equipe de Logística queria informar que seu pedido #458732 está a caminho e a previsão de chegada é terça-feira, das 14h às 18h.\n'

In [44]:
nova_lista_de_resumos2 = []
with open('lista_de_resumos.txt', 'r', encoding='utf-8') as arquivo:
    nova_lista_de_resumos2 = arquivo.readlines() 

nova_lista_de_resumos2

['E-mail 1: Mariana confirma a reunião de alinhamento de amanhã às 10h e pede que todos tragam as atualizações de suas tarefas.\n',
 'E-mail 2: A LojaOnline quer que você aproveite descontos de até 70% em eletrônicos e móveis neste fim de semana, válidos até domingo.\n',
 'E-mail 3: O Suporte Técnico alerta sobre um novo acesso desconhecido à sua conta e solicita que você altere sua senha imediatamente caso não o reconheça.\n',
 'E-mail 4: A pessoa queria convidar para o casamento de Ana e Lucas no dia 12 de dezembro às 17h.\n',
 'E-mail 5: Este email é uma **confirmação da sua reserva no Hotel Paraíso**, com check-in em 23/11 e check-out em 27/11.\n',
 'E-mail 6: A Equipe de Logística queria informar que seu pedido #458732 está a caminho e a previsão de chegada é terça-feira, das 14h às 18h.\n']

In [45]:
import pandas as pd

In [46]:
import csv
import random

# Dados de exemplo
nomes = [
    "Ana Silva", "Bruno Souza", "Carlos Pereira", "Daniela Lima", "Eduardo Castro",
    "Fernanda Alves", "Gabriel Rocha", "Helena Martins", "Igor Mendes", "Julia Santos"
]

# Gera médias aleatórias de 0 a 10
medias = [round(random.uniform(0, 10), 2) for _ in nomes]

# Cria o arquivo CSV
with open('notas.csv', 'w', newline='', encoding='utf-8') as arquivo:
    escritor = csv.writer(arquivo)
    escritor.writerow(["Nome", "Média"])  # Cabeçalho
    for nome, media in zip(nomes, medias):
        escritor.writerow([nome, media])

print("✅ Arquivo 'notas.csv' gerado com sucesso!")

✅ Arquivo 'notas.csv' gerado com sucesso!

In [47]:
df = pd.read_csv('notas.csv')

In [48]:
df

             Nome  Média
0       Ana Silva   4.24
1     Bruno Souza   3.98
2  Carlos Pereira   5.20
3    Daniela Lima   3.73
4  Eduardo Castro   9.79
5  Fernanda Alves   1.93
6   Gabriel Rocha   7.73
7  Helena Martins   9.68
8     Igor Mendes   0.38
9    Julia Santos   1.58

# Desafio

In [49]:
lista_de_perguntas = [
    'De que é feito o sol?',
    'De que é feito o planeta Saturno?',
    'Qual é a galáxia mais antiga já encontrada?',
    'Qual é a maior estrela já encontrada',
    'Qual é a estrela mais próxima do sol?'
]

# Cria o arquivo CSV
with open('perguntas.txt', 'w', newline='', encoding='utf-8') as arquivo:
    for pergunta in lista_de_perguntas:
        arquivo.write(pergunta + '\n')

print("✅ Arquivo 'perguntas.txt' gerado com sucesso!")

✅ Arquivo 'perguntas.txt' gerado com sucesso!

In [50]:
lista_perguntas = []
with open('perguntas.txt', 'r', encoding='utf-8') as arquivo:
    for linha in arquivo:
        lista_perguntas.append(linha.strip()) 

print(lista_perguntas)

['De que é feito o sol?', 'De que é feito o planeta Saturno?', 'Qual é a galáxia mais antiga já encontrada?', 'Qual é a maior estrela já encontrada', 'Qual é a estrela mais próxima do sol?']

In [51]:
def respostas(perguntas):
    lista_de_respostas = []

    for numero, perguntas in enumerate(perguntas):
        response = model.generate_content(f"""Gere uma respostas muito sucinta para a pergunta: {perguntas}""")
        print(f"Pergunta {numero + 1}:", response.text)
        lista_de_respostas.append(f'Pergunta {numero + 1}: {response.text}')
        print("-" * 50)
    


    return lista_de_respostas

In [53]:
lista_de_respostas = respostas(lista_perguntas)

Pergunta 1: Hidrogênio e Hélio.
--------------------------------------------------
Pergunta 2: Principalmente hidrogênio e hélio.
--------------------------------------------------
Pergunta 3: HD1.
--------------------------------------------------
Pergunta 4: UY Scuti.
--------------------------------------------------
Pergunta 5: Proxima Centauri.
--------------------------------------------------

In [54]:
dicionario = {
    'Pergunta': lista_de_perguntas,
    'Resposta': lista_de_respostas
}

In [55]:
print(lista_de_respostas)

['Pergunta 1: Hidrogênio e Hélio.', 'Pergunta 2: Principalmente hidrogênio e hélio.', 'Pergunta 3: HD1.', 'Pergunta 4: UY Scuti.', 'Pergunta 5: Proxima Centauri.']

In [65]:
# Cria o arquivo CSV
with open('respostas.csv', 'w', newline='', encoding='utf-8') as arquivo:
    escritor = csv.writer(arquivo)
    escritor.writerow(['pergunta', 'resposta'])
    for pergunta, resposta in zip(lista_de_perguntas, lista_de_respostas):
        escritor.writerow([pergunta, resposta])

print("✅ Arquivo 'respostas.csv' gerado com sucesso!")

✅ Arquivo 'respostas.csv' gerado com sucesso!

In [66]:


df = pd.DataFrame(dicionario)

In [67]:
df

,Pergunta,Resposta
0,De que é feito o sol?,Pergunta 1: Hidrogênio e Hélio.
1,De que é feito o planeta Saturno?,Pergunta 2: Principalmente hidrogênio e hélio.
2,Qual é a galáxia mais antiga já encontrada?,Pergunta 3: HD1.
3,Qual é a maior estrela já encontrada,Pergunta 4: UY Scuti.
4,Qual é a estrela mais próxima do sol?,Pergunta 5: Proxima Centauri.

In [68]:
import pandas as pd
import numpy as np
import random

# Gerar dados
produtos = [f"Produto {i}" for i in range(1, 51)]
categorias = ["Eletrônicos", "Roupas", "Alimentos", "Livros", "Brinquedos"]
precos = np.round(np.random.uniform(10, 2000, 50), 2)
quantidades = np.random.randint(1, 500, 50)
avaliacoes = np.round(np.random.uniform(1, 5, 50), 1)

# Criar DataFrame
df = pd.DataFrame({
    "produto": produtos,
    "categoria": [random.choice(categorias) for _ in range(50)],
    "preço": precos,
    "quantidade_vendida": quantidades,
    "avaliação_do_produto": avaliacoes
})

# Exibir DataFrame
print(df)

# (Opcional) Salvar em CSV
# df.to_csv("produtos.csv", index=False)

       produto    categoria    preço  quantidade_vendida  avaliação_do_produto
0    Produto 1  Eletrônicos  1208.53                 361                   3.1
1    Produto 2  Eletrônicos  1962.76                 142                   3.2
2    Produto 3       Livros  1279.53                 102                   4.7
3    Produto 4       Roupas   931.27                 474                   2.6
4    Produto 5       Livros  1014.16                  34                   4.2
5    Produto 6   Brinquedos   106.45                 250                   4.9
6    Produto 7    Alimentos  1687.53                 223                   1.7
7    Produto 8    Alimentos  1284.70                 366                   3.3
8    Produto 9       Roupas   187.47                  15                   1.2
9   Produto 10   Brinquedos   588.10                 393                   1.4
10  Produto 11       Livros   954.66                 181                   2.4
11  Produto 12       Livros  1236.18                  66                   4.8
12  Produto 13  Eletrônicos  1040.90                 376                   2.3
13  Produto 14       Livros   559.95                 297                   3.0
14  Produto 15  Eletrônicos   764.45                  67                   4.7
15  Produto 16       Roupas  1066.57                 449                   2.6
16  Produto 17  Eletrônicos   584.67                 308                   1.5
17  Produto 18    Alimentos   103.53                 262                   4.5
18  Produto 19  Eletrônicos  1852.31                  85                   3.5
19  Produto 20   Brinquedos  1044.05                 207                   3.1
20  Produto 21    Alimentos   426.24                 449                   1.3
21  Produto 22       Roupas   553.87                 172                   3.8
22  Produto 23   Brinquedos  1165.02                 392                   4.1
23  Produto 24       Livros   449.96                 128                   4.3
24  Produto 25    Alimentos  1394.54                 169                   3.5
25  Produto 26  Eletrônicos   729.73                 207                   1.9
26  Produto 27  Eletrônicos  1607.06                  65                   2.9
27  Produto 28   Brinquedos   825.88                 402                   2.8
28  Produto 29       Livros    38.47                 426                   2.7
29  Produto 30       Roupas  1882.77                 321                   1.4
30  Produto 31       Roupas  1936.24                 104                   4.0
31  Produto 32       Livros   393.84                  81                   1.5
32  Produto 33   Brinquedos   180.51                 138                   4.2
33  Produto 34       Roupas   955.31                 450                   2.3
34  Produto 35       Roupas   319.08                 294                   3.1
35  Produto 36       Roupas   561.87                 481                   3.3
36  Produto 37       Roupas  1199.30                 284                   3.1
37  Produto 38       Roupas   213.76                  91                   2.3
38  Produto 39       Roupas   941.87                 445                   1.7
39  Produto 40       Roupas  1501.21                  45                   4.4
40  Produto 41   Brinquedos  1285.89                  25                   4.1
41  Produto 42       Roupas   668.14                 300                   1.8
42  Produto 43    Alimentos  1923.10                 281                   1.7
43  Produto 44    Alimentos  1660.72                 368                   3.6
44  Produto 45    Alimentos   744.12                 342                   4.9
45  Produto 46       Livros   482.87                 234                   4.6
46  Produto 47    Alimentos   316.59                 275                   4.6
47  Produto 48  Eletrônicos    94.14                 471                   2.9
48  Produto 49    Alimentos  1251.95                 182                   1.6
49  Produto 50       Roupas  1890.61                   7                   2.1

In [69]:
df['categoria']

0     Eletrônicos
1     Eletrônicos
2          Livros
3          Roupas
4          Livros
5      Brinquedos
6       Alimentos
7       Alimentos
8          Roupas
9      Brinquedos
10         Livros
11         Livros
12    Eletrônicos
13         Livros
14    Eletrônicos
15         Roupas
16    Eletrônicos
17      Alimentos
18    Eletrônicos
19     Brinquedos
20      Alimentos
21         Roupas
22     Brinquedos
23         Livros
24      Alimentos
25    Eletrônicos
26    Eletrônicos
27     Brinquedos
28         Livros
29         Roupas
30         Roupas
31         Livros
32     Brinquedos
33         Roupas
34         Roupas
35         Roupas
36         Roupas
37         Roupas
38         Roupas
39         Roupas
40     Brinquedos
41         Roupas
42      Alimentos
43      Alimentos
44      Alimentos
45         Livros
46      Alimentos
47    Eletrônicos
48      Alimentos
49         Roupas
Name: categoria, dtype: object

In [70]:
df['categoria'].unique()

array(['Eletrônicos', 'Livros', 'Roupas', 'Brinquedos', 'Alimentos'],
      dtype=object)

In [71]:
set(df['categoria'])

{'Alimentos', 'Brinquedos', 'Eletrônicos', 'Livros', 'Roupas'}

In [75]:
# Filtragem

df[df['categoria'] == 'Eletrônicos']

       produto    categoria    preço  quantidade_vendida  avaliação_do_produto
0    Produto 1  Eletrônicos  1208.53                 361                   3.1
1    Produto 2  Eletrônicos  1962.76                 142                   3.2
12  Produto 13  Eletrônicos  1040.90                 376                   2.3
14  Produto 15  Eletrônicos   764.45                  67                   4.7
16  Produto 17  Eletrônicos   584.67                 308                   1.5
18  Produto 19  Eletrônicos  1852.31                  85                   3.5
25  Produto 26  Eletrônicos   729.73                 207                   1.9
26  Produto 27  Eletrônicos  1607.06                  65                   2.9
47  Produto 48  Eletrônicos    94.14                 471                   2.9

In [82]:
df[(df['categoria'] == 'Livros') & (df['preço'] > 550)]

       produto categoria    preço  quantidade_vendida  avaliação_do_produto
2    Produto 3    Livros  1279.53                 102                   4.7
4    Produto 5    Livros  1014.16                  34                   4.2
10  Produto 11    Livros   954.66                 181                   2.4
11  Produto 12    Livros  1236.18                  66                   4.8
13  Produto 14    Livros   559.95                 297                   3.0

In [76]:
df[df['avaliação_do_produto'] < 2]

       produto    categoria    preço  quantidade_vendida  avaliação_do_produto
6    Produto 7    Alimentos  1687.53                 223                   1.7
8    Produto 9       Roupas   187.47                  15                   1.2
9   Produto 10   Brinquedos   588.10                 393                   1.4
16  Produto 17  Eletrônicos   584.67                 308                   1.5
20  Produto 21    Alimentos   426.24                 449                   1.3
25  Produto 26  Eletrônicos   729.73                 207                   1.9
29  Produto 30       Roupas  1882.77                 321                   1.4
31  Produto 32       Livros   393.84                  81                   1.5
38  Produto 39       Roupas   941.87                 445                   1.7
41  Produto 42       Roupas   668.14                 300                   1.8
42  Produto 43    Alimentos  1923.10                 281                   1.7
48  Produto 49    Alimentos  1251.95                 182                   1.6

In [77]:
df[df['avaliação_do_produto'] < 2].shape

(12, 5)

In [83]:
df.iloc[15]

produto                 Produto 16
categoria                   Roupas
preço                      1066.57
quantidade_vendida             449
avaliação_do_produto           2.6
Name: 15, dtype: object

In [84]:
df.iloc[15:20]

       produto    categoria    preço  quantidade_vendida  avaliação_do_produto
15  Produto 16       Roupas  1066.57                 449                   2.6
16  Produto 17  Eletrônicos   584.67                 308                   1.5
17  Produto 18    Alimentos   103.53                 262                   4.5
18  Produto 19  Eletrônicos  1852.31                  85                   3.5
19  Produto 20   Brinquedos  1044.05                 207                   3.1

In [86]:
df_index = df.set_index('produto')
df_index

              categoria    preço  quantidade_vendida  avaliação_do_produto
produto
Produto 1   Eletrônicos  1208.53                 361                   3.1
Produto 2   Eletrônicos  1962.76                 142                   3.2
Produto 3        Livros  1279.53                 102                   4.7
Produto 4        Roupas   931.27                 474                   2.6
Produto 5        Livros  1014.16                  34                   4.2
Produto 6    Brinquedos   106.45                 250                   4.9
Produto 7     Alimentos  1687.53                 223                   1.7
Produto 8     Alimentos  1284.70                 366                   3.3
Produto 9        Roupas   187.47                  15                   1.2
Produto 10   Brinquedos   588.10                 393                   1.4
Produto 11       Livros   954.66                 181                   2.4
Produto 12       Livros  1236.18                  66                   4.8
Produto 13  Eletrônicos  1040.90                 376                   2.3
Produto 14       Livros   559.95                 297                   3.0
Produto 15  Eletrônicos   764.45                  67                   4.7
Produto 16       Roupas  1066.57                 449                   2.6
Produto 17  Eletrônicos   584.67                 308                   1.5
Produto 18    Alimentos   103.53                 262                   4.5
Produto 19  Eletrônicos  1852.31                  85                   3.5
Produto 20   Brinquedos  1044.05                 207                   3.1
Produto 21    Alimentos   426.24                 449                   1.3
Produto 22       Roupas   553.87                 172                   3.8
Produto 23   Brinquedos  1165.02                 392                   4.1
Produto 24       Livros   449.96                 128                   4.3
Produto 25    Alimentos  1394.54                 169                   3.5
Produto 26  Eletrônicos   729.73                 207                   1.9
Produto 27  Eletrônicos  1607.06                  65                   2.9
Produto 28   Brinquedos   825.88                 402                   2.8
Produto 29       Livros    38.47                 426                   2.7
Produto 30       Roupas  1882.77                 321                   1.4
Produto 31       Roupas  1936.24                 104                   4.0
Produto 32       Livros   393.84                  81                   1.5
Produto 33   Brinquedos   180.51                 138                   4.2
Produto 34       Roupas   955.31                 450                   2.3
Produto 35       Roupas   319.08                 294                   3.1
Produto 36       Roupas   561.87                 481                   3.3
Produto 37       Roupas  1199.30                 284                   3.1
Produto 38       Roupas   213.76                  91                   2.3
Produto 39       Roupas   941.87                 445                   1.7
Produto 40       Roupas  1501.21                  45                   4.4
Produto 41   Brinquedos  1285.89                  25                   4.1
Produto 42       Roupas   668.14                 300                   1.8
Produto 43    Alimentos  1923.10                 281                   1.7
Produto 44    Alimentos  1660.72                 368                   3.6
Produto 45    Alimentos   744.12                 342                   4.9
Produto 46       Livros   482.87                 234                   4.6
Produto 47    Alimentos   316.59                 275                   4.6
Produto 48  Eletrônicos    94.14                 471                   2.9
Produto 49    Alimentos  1251.95                 182                   1.6
Produto 50       Roupas  1890.61                   7                   2.1

In [90]:
df_index.loc['Produto 16']

categoria                Roupas
preço                   1066.57
quantidade_vendida          449
avaliação_do_produto        2.6
Name: Produto 16, dtype: object

In [92]:
df_index.loc['Produto 16':'Produto 20']

              categoria    preço  quantidade_vendida  avaliação_do_produto
produto
Produto 16       Roupas  1066.57                 449                   2.6
Produto 17  Eletrônicos   584.67                 308                   1.5
Produto 18    Alimentos   103.53                 262                   4.5
Produto 19  Eletrônicos  1852.31                  85                   3.5
Produto 20   Brinquedos  1044.05                 207                   3.1

In [94]:
df_index.loc[['Produto 16','Produto 20'], ['categoria', 'preço']]

             categoria    preço
produto
Produto 16      Roupas  1066.57
Produto 20  Brinquedos  1044.05

In [100]:
brinquedos = df_index[df_index['categoria'] == 'Brinquedos']
df_index.loc[brinquedos.index, 'categoria'] = 'infantojuvenil'

In [104]:
df_index['categoria'].unique()

array(['Eletrônicos', 'Livros', 'Roupas', 'infantojuvenil', 'Alimentos'],
      dtype=object)

In [116]:
# Desafio

reviews = pd.read_csv('reviews.csv')
reviews

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0
5,A2Q3ICGWZLY3JJ,B007WTAJTO,98020,"It works, but file writes are a bit slower tha...",1384905600,20/11/2013,383,0,0
6,AF24M1HKIZ7QC,B007WTAJTO,"Abdulrahman J. Alrashed ""dr34m3r""","I bought 2 of those SanDisk 32 GB microSD , us...",1375488000,08/03/2013,640,0,0
7,A1KIF9Z5VFPH7H,B007WTAJTO,"Abel Feliciano ""Ace Master""",The memory card is an excellent condition and ...,1347321600,09/11/2012,759,0,0
8,A1FKE13D77L3Y3,B007WTAJTO,Abraham Arturo Meza Marin,I bougth this micro SD card after some trubles...,1361232000,19/02/2013,657,0,0
9,A1X1FX3NSOFCT3,B007WTAJTO,"Abused Commuter ""abused_commuter""",Ordered this for a Galaxy S3. Lasted a few mo...,1374278400,20/07/2013,506,0,1
10,A3RV1L35IPTV61,B007WTAJTO,abushaheed,more like 8mb/s in my Note 10.1 and that's usi...,1357430400,01/06/2013,555,0,0
11,A2RJ7DAL63MN1F,B007WTAJTO,Ace of Sevens,"I used this for a few months in my phone, then...",1391126400,31/01/2014,311,0,0
12,A3IJIFZ5HH819V,B007WTAJTO,A. Cho,"everything about it was great, except for the ...",1373414400,07/10/2013,427,0,0
13,A1R0JMNRV7HVQM,B007WTAJTO,ACZ,Used in my phone it's plenty fast and works ju...,1383609600,11/05/2013,576,0,0
14,APAEBFIM1588A,B007WTAJTO,"Adam Wright ""Electrical Engineer""",This card advertises itself as UHS1 but it's a...,1378684800,09/09/2013,455,1,1
15,A1JOXGZH55JMHW,B007WTAJTO,A. Hejazi,I bought this SD card for my android phone thi...,1386806400,12/12/2013,361,0,0
16,A35NR2GQWMQ31K,B007WTAJTO,ahhsimon,good card. work as describes. haven't had any ...,1391644800,02/06/2014,189,0,0
17,A1N7LGUPJWWQS9,B007WTAJTO,A.J. Matheson,I got this because I just couldn't pass up the...,1353888000,26/11/2012,742,0,0
18,A28CTDM7OP0RAR,B007WTAJTO,Alan,It works but the actual R/W speeds are 18/8 MB...,1395705600,25/03/2014,258,0,0
19,A1NA2JGI3GNDN2,B007WTAJTO,Albert,Does it's job and fairly cheap for what it's w...,1399161600,05/04/2014,247,0,0
20,A3PCW69GQK8R38,B007WTAJTO,Alejandro Hernndez,Still don't feel is very fast or is just my ph...,1391385600,02/03/2014,281,0,0
21,A1UM44ILLZCEI1,B007WTAJTO,Aleksandar Milivojevic,I bought 64GB version of the card to use with ...,1364947200,04/03/2013,644,1,1
22,A2T71JNR3C2DY1,B007WTAJTO,"Ali Etezadkhah ""Ali""",I have an old SanDisk SD card that still works...,1371859200,22/06/2013,534,0,0
23,A87U7LY9OKZNY,B007WTAJTO,A. Liu,Used it in my Galaxy Note 2 for the past 16 mo...,1398988800,05/02/2014,306,0,0
24,A277QWS5WF6DWI,B007WTAJTO,Alton L Spencer,Worked great in my galaxy s4--until it didn't ...,1401148800,27/05/2014,195,0,0
25,A1WWPAQ1DD6BQC,B007WTAJTO,A. Marte,I bought this on August of 2013. As of April ...,1403654400,25/06/2014,166,1,1
26,A3FY6V3LXP8SSL,B007WTAJTO,"Amazon Customer ""fiction buff""",So this product is a large disappointment...bo...,1349136000,10/02/2012,1032,0,0
27,A3DXCQV1U6QLTS,B007WTAJTO,Amazon Customer,I will keep it short and sweet for potential b...,1360195200,02/07/2013,524,0,0
28,A3R2TY7PFN9VSM,B007WTAJTO,Amazon Customer,"The package arrived on time, it's very well pa...",1375660800,08/05/2013,579,0,0
29,A1FZKP9XTKMALD,B007WTAJTO,Amazon Customer,"Does what it says. Hasn't broken yet, and I ho...",1375401600,08/02/2013,668,0,1
30,A308JP3BK4VAL7,B007WTAJTO,Amazon Customer,Thus microSD card worked fine for a year in my...,1398643200,28/04/2014,224,0,3
31,A392ZR68AKLDCK,B007WTAJTO,"Amazon Customer ""Music Fan""","I think this is probably a fine product, but i...",1374796800,26/07/2013,500,1,1
32,A2DQ2U5BYIXNUJ,B007WTAJTO,"Amazon Customer ""PawsitivelySafe""",I have two of these and use them for my Galazy...,1387152000,16/12/2013,357,0,0
33,A14D2PS27PI3FM,B007WTAJTO,Amazon Fan,I join the long list of customers who have had...,1359936000,02/04/2013,615,1,2
34,A1Z7FZP81N8CDU,B007WTAJTO,Amazon Shopper,"I do not get the advertised speed of 30MB/s, m...",1394755200,14/03/2014,269,0,1
35,A1T8FVB93QQNOM,B007WTAJTO,Andrew M. Swiatek,the micro sd works great as described. but bew...,1372464000,29/06/2013,527,0,0
36,A3K1JZPUXSADRJ,B007WTAJTO,anonomous,than i expected. I don't know if it would kill...,1362182400,03/02/2013,673,0,2
37,A1D07XDTMWV0A5,B007WTAJTO,"A. Shieh ""eff.org""","Reliable and inexpensive. However, it's quite ...",1385769600,30/11/2013,373,0,0
38,A1HKW2TELCHGLL,B007WTAJTO,astraelraen,I bought this primarily to use in my Surface P...,1391040000,30/01/2014,312,0,0
39,A3P86Z2D81VLYV,B007WTAJTO,"Zeality ""N2iT""",I really don't know what to think about this I...,1396137600,30/03/2014,253,0,0

In [121]:
import time

In [140]:

reviews['sentimento'] = ''
reviews = reviews[['reviewText', 'sentimento']]
reviews = reviews.head(20)

for i, texto in enumerate(reviews['reviewText']):
    response = model.generate_content(f"Analise o sentimento do seguinte texto e diga se é positivo, negativo ou neutro: '{texto}'. Você deve responder apenas com uma palavra: positivo, negativo ou neutro.")
    reviews.loc[i, 'sentimento'] = response.text.strip()
    # Pequena pausa para evitar limite de requisições
    time.sleep(0.5)

In [137]:
reviews

                                          reviewText sentimento
0  it works as expected. I should have sprung for...   Negativo
1  This think has worked out great.Had a diff. br...   Positivo
2  Bought it with Retail Packaging, arrived legit...   Positivo
3  It's mini storage.  It doesn't do anything els...   Positivo
4  I have it in my phone and it never skips a bea...   positivo
5  It works, but file writes are a bit slower tha...     neutro
6  I bought 2 of those SanDisk 32 GB microSD , us...   negativo
7  The memory card is an excellent condition and ...   Positivo
8  I bougth this micro SD card after some trubles...   negativo
9  Ordered this for a Galaxy S3.  Lasted a few mo...   Negativo

In [138]:
# Tratamento de erros com try, except, else e finally

try:
    # Tenta executar o código principal
    num = int(input("Digite um número: "))
    resultado = 10 / num
    print(f"✅ Resultado da divisão: {resultado}")

except ZeroDivisionError as e:
    # Mensagem para o usuário
    print("❌ Erro: não é possível dividir por zero.")
    # Mensagem para o desenvolvedor
    print(f"[DEBUG - Desenvolvedor] Tipo do erro: {type(e).__name__} | Detalhes: {e}")

except ValueError as e:
    print("❌ Erro: entrada inválida. Digite um número inteiro.")
    print(f"[DEBUG - Desenvolvedor] Tipo do erro: {type(e).__name__} | Detalhes: {e}")

except Exception as e:
    # Captura qualquer outro erro inesperado
    print("⚠️ Ocorreu um erro inesperado.")
    print(f"[DEBUG - Desenvolvedor] Tipo do erro: {type(e).__name__} | Detalhes: {e}")

finally:
    print("🔚 Execução finalizada (este bloco roda sempre).")

✅ Resultado da divisão: 10.0
🔚 Execução finalizada (este bloco roda sempre).

In [139]:

reviews['sentimento'] = reviews['sentimento'].str.upper()
reviews_neg = reviews[reviews['sentimento'] == 'NEGATIVO']
reviews_neg = reviews_neg['reviewText']
reviews_neg

0    it works as expected. I should have sprung for...
6    I bought 2 of those SanDisk 32 GB microSD , us...
8    I bougth this micro SD card after some trubles...
9    Ordered this for a Galaxy S3.  Lasted a few mo...
Name: reviewText, dtype: object

In [135]:
reviews_neg_unidas = "#####".join(reviews_neg)

In [ ]:

for i, texto in enumerate(reviews['reviewText']):
    response = model.generate_content(f"Você um especialista em dados. Vou te passar muitas resenhas negativas de análises de um produto, e eu quero que você encontre 5 categorias diferentes para os tipos de reclamação. Quero que vc me retorne as 5 categorias.
                                      reviews_neg_unidas = '{reviews_neg_unidas}'")
    reviews.loc[i, 'sentimento'] = response.text.strip()
    # Pequena pausa para evitar limite de requisições
    time.sleep(0.5)

In [6]:
from openai import OpenAI

In [12]:
from openai import OpenAI

client_openai = OpenAI(
    base_url="http://127.0.0.1:1234/v1",
    api_key="local"  # qualquer valor serve quando rodando localmente
)

resposta_do_llm = client_openai.chat.completions.create(
    model="google/gemma-3-1b",
    messages=[
        {"role": "user", "content": "O que é IA?"}
    ],
    temperature=0
)

print(resposta_do_llm.choices[0].message.content)

IA, ou Inteligência Artificial, é um campo da ciência da computação que se dedica a criar sistemas e máquinas capazes de simular a inteligência humana. Em vez de simplesmente seguir instruções programadas para realizar tarefas repetitivas, a IA busca desenvolver sistemas que possam aprender, raciocinar, resolver problemas, perceber o ambiente e até mesmo entender linguagem natural.

**Em termos mais simples:** A IA é sobre dar aos computadores a capacidade de "pensar" como os humanos, ou pelo menos simular esse comportamento.

**Existem diferentes tipos de IA:**

*   **IA Estreita (ou Fraca):** Projetada para realizar uma tarefa específica com alta precisão. Exemplos: reconhecimento facial, tradução automática, sistemas de recomendação de produtos.
*   **IA Geral (ou Forte):** Possui a capacidade de entender, aprender e aplicar o conhecimento em qualquer tarefa intelectual que um ser humano pode fazer. Ainda é um objetivo distante da IA atual.
*   **Superinteligência:** Um nível hipotético de IA que supera a inteligência humana em todos os aspectos.

**Como funciona?**

A IA utiliza diversas técnicas, incluindo:

*   **Aprendizado de Máquina (Machine Learning):**  É o método mais comum atualmente. Os algoritmos de aprendizado de máquina analisam grandes quantidades de dados para identificar padrões e aprender a partir deles.
*   **Redes Neurais:** Inspiradas no cérebro humano, as redes neurais são usadas para processar informações complexas como imagens, áudio e texto.
*   **Processamento de Linguagem Natural (NLP):** Permite que os computadores entendam e processem a linguagem humana.
*   **Visão Computacional:**  Permite que os computadores "vejam" e interpretem imagens e vídeos.

**Aplicações da IA no dia a dia:**

A IA já está presente em muitas áreas da nossa vida, como:

*   Assistentes virtuais (Siri, Alexa, Google Assistant)
*   Recomendação de filmes e músicas
*   Carros autônomos
*   Diagnóstico médico
*   Detecção de fraudes
*   Chatbots para atendimento ao cliente

**Em resumo:** A IA é uma área em constante evolução com o potencial de transformar a forma como vivemos e trabalhamos. É um campo fascinante que está moldando o futuro da tecnologia e da sociedade.

Você gostaria de saber mais sobre algum aspecto específico da IA, como:

*   Alguns exemplos de aplicações atuais?
*   Como funciona o aprendizado de máquina em detalhes?
*   O futuro da IA?

# Desafio Final

In [13]:
# Etapa 1: Ler o arquivo de resenhas

lista_de_resenhas = []
with open('Resenhas_App_ChatGPT.txt', 'r', encoding='utf-8') as arquivo:
    for linha in arquivo:
       lista_de_resenhas.append(linha.strip())

print(lista_de_resenhas)

["53409593$Safoan Riyad$J'aimais bien ChatGPT. Mais la dernière mise à jour a tout gâché. Elle a tout oublié.", '39485494$Habimana Therese$This app is very important but sometimes it gives lies', '4549594$Shahidatun jannat$Wonderful app..i just aastonished.. love this app..', '890535$Rayyan R$Anytime i try to get the app to work. It tells me "an error has occured" can this be fixed', '3590353$Nkanyi Cele$Acabo de instalar la aplicación desde Google Play Store, pero lamentablemente no se abre. Se queda dando vueltas.', '94824834$Jayanth Pudducheri$Gerçekten harika, günlük ya?am için çok ihtiyaç duyulan bir uygulama', '73875305$saikat das$You guys are rocking. Out of this world, feels like Matrix.', "37895234$Mohamedi Mustapha$It's incredible help me to my university education Carrer", '28942747$James Williams$this ai app has some good features but it is lacking in understanding.', "93457830$Alexis$Cool, just wish there wasn't a limit for the free trial to be honest", "2892445$Mark Feldman$L'IA est géniale, mais pour une raison inconnue, elle s'arrête sans arrêt, me dit «\xa0Une erreur s'est produite\xa0» et m'empêche totalement de l'utiliser. C'est vraiment dommage.", '83487232$Somshuvra Saha$Database too old to use. No database opdate after that. It can give information regarding recent events. Gemini is best which can give real time information.', '304724$Ahmad Raza$very good but it would be better if the normal version responded fast', '23480294$Andrew MacKay$Voice frequently disconnects, and finding specific chats would be easier if we could tag them and filter by tag or custom gpt.', '537857340$Kavya Kavya$je?li jest za darmo to daj? 5 gwiazdek ze wzgl?du na czat gpt 4.0 jak wiemy nie jest za darmo wi?c tylko 3 gwiazdki', '34853495$Vaishnavi Tandon$To use it a lot of improvements are still needed, specially for Indian', '74548903$Hdfc Gg$App is cool but developer should add more features on this app, like-generating photos and videos', '3589893$Yavuz YurtbeÄ\x9fendi$Does not work on my tablet, it is stuck at loading screen', '845030$Eyob Getachew$Aplica?ia e destul de bun?, dar dac? exist? acces la fotografii ar fi grozav, cum ar fi întrebarea cu inteligen?a artificial?, îmi place mai mult op?iunea asta ?i cred c? e ideea fiec?ruia.', "49078284$Hrushi Padia$I am unable to understand the symbols of mathematics as they are not getting converted. For example the multiplication sign i.e. Ã\x97 is shown as \\times_6 and same for all the symbols. I can't understand the sum as it gets hard to read.", "2740724$Karli du Plessis$Lo adoro, lo uso per cose molto dialogate, ma ora con il limite di messaggi, a mio parere è un po' ingiusto, nonostante le intenzioni. Non voglio usare la versione premium perché la versione gratuita ha sempre funzionato perfettamente per me. Non c'è un modo alternativo per gestirlo, oltre a imporre limiti praticamente a tutto?Isn't there an alternative way to manage it other than putting limits on literally everything?", '84278942$jason yones$I like it but it always say "I cannot assist with that" for no reason, it just basically say the same word', '27042703$Ibrahim Ghani$Middling experience. The web version feels nicer. This app feels... Obese.', '47985785$AMISHA BESRA$något visar ett oöverträffat svar och en del information matchar inte det givna ämnet']

In [37]:
# Exemplo de resenha
linha_teste = "João: The app keeps crashing every time I open it. Terrible experience!"

# Chama a função já definida
resposta = recebe_linha_e_retorna_json(linha_teste)

In [39]:
print(resposta)

```json
{
  "usuario": "João",
  "resenha_original": "The app keeps crashing every time I open it. Terrible experience!",
  "resenha_pt": "O aplicativo trava a cada vez que eu o abro. Uma experiência terrível!",
  "avaliação": "negativa"
}
```

In [41]:
resposta = resposta.replace("```json", "").replace("```", "")
print(resposta)

{
  "usuario": "João",
  "resenha_original": "The app keeps crashing every time I open it. Terrible experience!",
  "resenha_pt": "O aplicativo trava a cada vez que eu o abro. Uma experiência terrível!",
  "avaliação": "negativa"
}

In [ ]:
# Etapa 2 e 3

from phyton_ia.contato_com_llm import recebe_linha_e_retorna_json
import json

lista_de_resenhas_json = []

for resenha in lista_de_resenhas:
    resposta_json = recebe_linha_e_retorna_json(resenha)
    #resposta_json = resposta_json.replace("```json", "").replace("```", "")
    resenha_dict = []
    lista_de_resenhas_json.append(resenha_dict)

In [ ]:
# Etapa 4

def contador_e_juntador(lista_de_dicionarios):
    contador_positivas = 0
    contador_negativas = 0
    contador_neutras = 0

    for dicionario in lista_de_dicionarios:
        if dicionario['sentimento'] == 'positivo':
            contador_positivas += 1
        elif dicionario['sentimento'] == 'negativo':
            contador_negativas += 1
        else:
            contador_neutras += 1

        lista_de_dicionarios_str = [str(dicionario) for dicionario in lista_de_dicionarios]
        textos_juntos = " ##### ".join(lista_de_dicionarios_str)

    return contador_positivas, contador_negativas, contador_neutras, textos_juntos

pos, neg, neut, textos = contador_e_juntador(lista_de_resenhas_json)

print(f'Positivas: {pos}')
print(f'Negativas: {neg}')
print(f'Neutras: {neut}')
print(textos)